# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\LASDiAGUI.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LASDiAGUI(object):
    def setupUi(self, LASDiAGUI):
        LASDiAGUI.setObjectName("LASDiAGUI")
        LASDiAGUI.resize(1385, 910)
        self.expPanel = QtWidgets.QTabWidget(LASDiAGUI)
        self.expPanel.setGeometry(QtCore.QRect(710, 0, 641, 261))
        self.expPanel.setAutoFillBackground(False)
        self.expPanel.setStyleSheet("")
        self.expPanel.setObjectName("expPanel")
        self.fileTab = QtWidgets.QWidget()
        self.fileTab.setObjectName("fileTab")
        self.num_interpolation_2 = QtWidgets.QLabel(self.fileTab)
        self.num_interpolation_2.setGeometry(QtCore.QRect(160, 180, 91, 16))
        self.num_interpolation_2.setObjectName("num_interpolation_2")
        self.importData = QtWidgets.QPushButton(self.fileTab)
        self.importData.setGeometry(QtCore.QRect(10, 20, 115, 32))
        self.importData.setStyleSheet("")
        self.importData.setObjectName("importData")
        self.interpolationData = QtWidgets.QPushButton(self.fileTab)
        self.interpolationData.setGeometry(QtCore.QRect(10, 170, 115, 32))
        self.interpolationData.setObjectName("interpolationData")
        self.removePeaksData = QtWidgets.QPushButton(self.fileTab)
        self.removePeaksData.setGeometry(QtCore.QRect(10, 110, 115, 32))
        self.removePeaksData.setObjectName("removePeaksData")
        self.fileSampleName = QtWidgets.QTextEdit(self.fileTab)
        self.fileSampleName.setGeometry(QtCore.QRect(170, 20, 381, 31))
        self.fileSampleName.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.fileSampleName.setObjectName("fileSampleName")
        self.numInterpData = QtWidgets.QSpinBox(self.fileTab)
        self.numInterpData.setGeometry(QtCore.QRect(250, 180, 42, 22))
        self.numInterpData.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.numInterpData.setObjectName("numInterpData")
        self.expPanel.addTab(self.fileTab, "")
        self.bkgTab = QtWidgets.QWidget()
        self.bkgTab.setObjectName("bkgTab")
        self.fileBkgName = QtWidgets.QTextEdit(self.bkgTab)
        self.fileBkgName.setGeometry(QtCore.QRect(170, 20, 381, 31))
        self.fileBkgName.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.fileBkgName.setObjectName("fileBkgName")
        self.scaleValue_2 = QtWidgets.QLabel(self.bkgTab)
        self.scaleValue_2.setGeometry(QtCore.QRect(170, 110, 59, 16))
        self.scaleValue_2.setObjectName("scaleValue_2")
        self.numInterpolation_2 = QtWidgets.QLabel(self.bkgTab)
        self.numInterpolation_2.setGeometry(QtCore.QRect(160, 180, 91, 16))
        self.numInterpolation_2.setObjectName("numInterpolation_2")
        self.importBkg = QtWidgets.QPushButton(self.bkgTab)
        self.importBkg.setGeometry(QtCore.QRect(10, 20, 115, 32))
        self.importBkg.setObjectName("importBkg")
        self.scaleValue = QtWidgets.QDoubleSpinBox(self.bkgTab)
        self.scaleValue.setGeometry(QtCore.QRect(250, 110, 66, 24))
        self.scaleValue.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.scaleValue.setObjectName("scaleValue")
        self.interpolationBkg = QtWidgets.QPushButton(self.bkgTab)
        self.interpolationBkg.setGeometry(QtCore.QRect(10, 170, 115, 32))
        self.interpolationBkg.setObjectName("interpolationBkg")
        self.removePeaksBkg = QtWidgets.QPushButton(self.bkgTab)
        self.removePeaksBkg.setGeometry(QtCore.QRect(10, 110, 115, 32))
        self.removePeaksBkg.setObjectName("removePeaksBkg")
        self.numInterpBkg = QtWidgets.QSpinBox(self.bkgTab)
        self.numInterpBkg.setGeometry(QtCore.QRect(250, 180, 42, 22))
        self.numInterpBkg.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.numInterpBkg.setObjectName("numInterpBkg")
        self.expPanel.addTab(self.bkgTab, "")
        self.geometryTab = QtWidgets.QWidget()
        self.geometryTab.setObjectName("geometryTab")
        self.xray_energy_2 = QtWidgets.QLabel(self.geometryTab)
        self.xray_energy_2.setGeometry(QtCore.QRect(20, 10, 121, 16))
        self.xray_energy_2.setStyleSheet("")
        self.xray_energy_2.setObjectName("xray_energy_2")
        self.xray_energy = QtWidgets.QDoubleSpinBox(self.geometryTab)
        self.xray_energy.setGeometry(QtCore.QRect(130, 10, 66, 24))
        self.xray_energy.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.xray_energy.setObjectName("xray_energy")
        self.dacCorrection = QtWidgets.QGroupBox(self.geometryTab)
        self.dacCorrection.setGeometry(QtCore.QRect(10, 50, 361, 51))
        self.dacCorrection.setObjectName("dacCorrection")
        self.dac_thickness = QtWidgets.QDoubleSpinBox(self.dacCorrection)
        self.dac_thickness.setGeometry(QtCore.QRect(110, 20, 66, 24))
        self.dac_thickness.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.dac_thickness.setDecimals(4)
        self.dac_thickness.setMaximum(99.9999)
        self.dac_thickness.setObjectName("dac_thickness")
        self.dac_thickness_2 = QtWidgets.QLabel(self.dacCorrection)
        self.dac_thickness_2.setGeometry(QtCore.QRect(10, 20, 101, 16))
        self.dac_thickness_2.setObjectName("dac_thickness_2")
        self.dac_angle = QtWidgets.QDoubleSpinBox(self.dacCorrection)
        self.dac_angle.setGeometry(QtCore.QRect(290, 20, 66, 24))
        self.dac_angle.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.dac_angle.setObjectName("dac_angle")
        self.dac_angle_2 = QtWidgets.QLabel(self.dacCorrection)
        self.dac_angle_2.setGeometry(QtCore.QRect(190, 20, 101, 16))
        self.dac_angle_2.setObjectName("dac_angle_2")
        self.MCCCorrection = QtWidgets.QGroupBox(self.geometryTab)
        self.MCCCorrection.setGeometry(QtCore.QRect(10, 110, 281, 111))
        self.MCCCorrection.setObjectName("MCCCorrection")
        self.ws1_2 = QtWidgets.QLabel(self.MCCCorrection)
        self.ws1_2.setGeometry(QtCore.QRect(10, 20, 51, 16))
        self.ws1_2.setObjectName("ws1_2")
        self.ws1 = QtWidgets.QDoubleSpinBox(self.MCCCorrection)
        self.ws1.setGeometry(QtCore.QRect(70, 20, 66, 24))
        self.ws1.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.ws1.setDecimals(4)
        self.ws1.setMaximum(99.9999)
        self.ws1.setObjectName("ws1")
        self.r1 = QtWidgets.QDoubleSpinBox(self.MCCCorrection)
        self.r1.setGeometry(QtCore.QRect(70, 50, 66, 24))
        self.r1.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.r1.setDecimals(4)
        self.r1.setMaximum(99.9999)
        self.r1.setObjectName("r1")
        self.r2 = QtWidgets.QDoubleSpinBox(self.MCCCorrection)
        self.r2.setGeometry(QtCore.QRect(210, 50, 66, 24))
        self.r2.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.r2.setDecimals(4)
        self.r2.setMaximum(99.9999)
        self.r2.setObjectName("r2")
        self.d_2 = QtWidgets.QLabel(self.MCCCorrection)
        self.d_2.setGeometry(QtCore.QRect(10, 80, 51, 16))
        self.d_2.setObjectName("d_2")
        self.ws2_2 = QtWidgets.QLabel(self.MCCCorrection)
        self.ws2_2.setGeometry(QtCore.QRect(150, 20, 51, 16))
        self.ws2_2.setObjectName("ws2_2")
        self.ws2 = QtWidgets.QDoubleSpinBox(self.MCCCorrection)
        self.ws2.setGeometry(QtCore.QRect(210, 20, 66, 24))
        self.ws2.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.ws2.setDecimals(4)
        self.ws2.setMaximum(99.9999)
        self.ws2.setObjectName("ws2")
        self.r1_2 = QtWidgets.QLabel(self.MCCCorrection)
        self.r1_2.setGeometry(QtCore.QRect(10, 50, 51, 16))
        self.r1_2.setObjectName("r1_2")
        self.d = QtWidgets.QDoubleSpinBox(self.MCCCorrection)
        self.d.setGeometry(QtCore.QRect(70, 80, 66, 24))
        self.d.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.d.setDecimals(4)
        self.d.setMaximum(99.9999)
        self.d.setObjectName("d")
        self.r2_2 = QtWidgets.QLabel(self.MCCCorrection)
        self.r2_2.setGeometry(QtCore.QRect(150, 50, 51, 16))
        self.r2_2.setObjectName("r2_2")
        self.expPanel.addTab(self.geometryTab, "")
        self.sampleTab = QtWidgets.QWidget()
        self.sampleTab.setObjectName("sampleTab")
        self.importXYZFile = QtWidgets.QPushButton(self.sampleTab)
        self.importXYZFile.setGeometry(QtCore.QRect(430, 190, 115, 32))
        self.importXYZFile.setObjectName("importXYZFile")
        self.comboBox = QtWidgets.QComboBox(self.sampleTab)
        self.comboBox.setGeometry(QtCore.QRect(10, 70, 69, 22))
        self.comboBox.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.sampleTab)
        self.pushButton.setGeometry(QtCore.QRect(10, 20, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.sampleTab)
        self.pushButton_2.setGeometry(QtCore.QRect(100, 20, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.sampleTab)
        self.pushButton_3.setGeometry(QtCore.QRect(280, 20, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.sampleTab)
        self.pushButton_4.setGeometry(QtCore.QRect(190, 20, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.calcSQ = QtWidgets.QPushButton(self.sampleTab)
        self.calcSQ.setGeometry(QtCore.QRect(10, 180, 75, 23))
        self.calcSQ.setObjectName("calcSQ")
        self.calcFr = QtWidgets.QPushButton(self.sampleTab)
        self.calcFr.setGeometry(QtCore.QRect(10, 210, 75, 23))
        self.calcFr.setObjectName("calcFr")
        self.expPanel.addTab(self.sampleTab, "")
        self.overlayTab = QtWidgets.QWidget()
        self.overlayTab.setObjectName("overlayTab")
        self.expPanel.addTab(self.overlayTab, "")
        self.analysisPanel = QtWidgets.QGroupBox(LASDiAGUI)
        self.analysisPanel.setGeometry(QtCore.QRect(710, 260, 641, 521))
        self.analysisPanel.setObjectName("analysisPanel")
        self.NonOptimizeParam = QtWidgets.QGroupBox(self.analysisPanel)
        self.NonOptimizeParam.setGeometry(QtCore.QRect(0, 10, 641, 121))
        self.NonOptimizeParam.setTitle("")
        self.NonOptimizeParam.setObjectName("NonOptimizeParam")
        self.smoothFactor = QtWidgets.QDoubleSpinBox(self.NonOptimizeParam)
        self.smoothFactor.setGeometry(QtCore.QRect(100, 10, 71, 24))
        self.smoothFactor.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.smoothFactor.setMaximum(1000.0)
        self.smoothFactor.setProperty("value", 0.25)
        self.smoothFactor.setObjectName("smoothFactor")
        self.smoothFactor_2 = QtWidgets.QLabel(self.NonOptimizeParam)
        self.smoothFactor_2.setGeometry(QtCore.QRect(10, 10, 91, 16))
        self.smoothFactor_2.setObjectName("smoothFactor_2")
        self.maxQ = QtWidgets.QDoubleSpinBox(self.NonOptimizeParam)
        self.maxQ.setGeometry(QtCore.QRect(520, 90, 66, 24))
        self.maxQ.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.maxQ.setMaximum(1000.0)
        self.maxQ.setProperty("value", 109.0)
        self.maxQ.setObjectName("maxQ")
        self.dampFactor_2 = QtWidgets.QLabel(self.NonOptimizeParam)
        self.dampFactor_2.setGeometry(QtCore.QRect(10, 50, 91, 16))
        self.dampFactor_2.setObjectName("dampFactor_2")
        self.iterations_2 = QtWidgets.QLabel(self.NonOptimizeParam)
        self.iterations_2.setGeometry(QtCore.QRect(220, 10, 101, 16))
        self.iterations_2.setObjectName("iterations_2")
        self.iterations = QtWidgets.QSpinBox(self.NonOptimizeParam)
        self.iterations.setGeometry(QtCore.QRect(300, 10, 66, 24))
        self.iterations.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.iterations.setMaximum(99)
        self.iterations.setProperty("value", 2)
        self.iterations.setObjectName("iterations")
        self.dampFactor = QtWidgets.QDoubleSpinBox(self.NonOptimizeParam)
        self.dampFactor.setGeometry(QtCore.QRect(100, 50, 71, 24))
        self.dampFactor.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.dampFactor.setMaximum(1000.0)
        self.dampFactor.setProperty("value", 1.0)
        self.dampFactor.setObjectName("dampFactor")
        self.minQ = QtWidgets.QDoubleSpinBox(self.NonOptimizeParam)
        self.minQ.setGeometry(QtCore.QRect(520, 10, 66, 24))
        self.minQ.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.minQ.setMaximum(1000.0)
        self.minQ.setProperty("value", 3.0)
        self.minQ.setObjectName("minQ")
        self.maxQ_2 = QtWidgets.QLabel(self.NonOptimizeParam)
        self.maxQ_2.setGeometry(QtCore.QRect(420, 90, 71, 16))
        self.maxQ_2.setObjectName("maxQ_2")
        self.minQ_2 = QtWidgets.QLabel(self.NonOptimizeParam)
        self.minQ_2.setGeometry(QtCore.QRect(420, 10, 71, 16))
        self.minQ_2.setObjectName("minQ_2")
        self.QmaxInt_2 = QtWidgets.QLabel(self.NonOptimizeParam)
        self.QmaxInt_2.setGeometry(QtCore.QRect(420, 50, 91, 16))
        self.QmaxInt_2.setObjectName("QmaxInt_2")
        self.QmaxInt = QtWidgets.QDoubleSpinBox(self.NonOptimizeParam)
        self.QmaxInt.setGeometry(QtCore.QRect(520, 50, 66, 24))
        self.QmaxInt.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.QmaxInt.setMaximum(1000.0)
        self.QmaxInt.setProperty("value", 98.0)
        self.QmaxInt.setObjectName("QmaxInt")
        self.OptimizeParam = QtWidgets.QGroupBox(self.analysisPanel)
        self.OptimizeParam.setGeometry(QtCore.QRect(0, 130, 641, 391))
        self.OptimizeParam.setTitle("")
        self.OptimizeParam.setObjectName("OptimizeParam")
        self.sfValue = QtWidgets.QDoubleSpinBox(self.OptimizeParam)
        self.sfValue.setGeometry(QtCore.QRect(140, 60, 66, 24))
        self.sfValue.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.sfValue.setMaximum(1000.0)
        self.sfValue.setProperty("value", 0.81)
        self.sfValue.setObjectName("sfValue")
        self.rmin = QtWidgets.QDoubleSpinBox(self.OptimizeParam)
        self.rmin.setGeometry(QtCore.QRect(140, 100, 66, 24))
        self.rmin.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.rmin.setMaximum(1000.0)
        self.rmin.setProperty("value", 0.24)
        self.rmin.setObjectName("rmin")
        self.rho0Value_2 = QtWidgets.QLabel(self.OptimizeParam)
        self.rho0Value_2.setGeometry(QtCore.QRect(10, 20, 101, 16))
        self.rho0Value_2.setObjectName("rho0Value_2")
        self.rho0Value = QtWidgets.QDoubleSpinBox(self.OptimizeParam)
        self.rho0Value.setGeometry(QtCore.QRect(140, 20, 66, 24))
        self.rho0Value.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.rho0Value.setMaximum(1000.0)
        self.rho0Value.setProperty("value", 27.18)
        self.rho0Value.setObjectName("rho0Value")
        self.sfValue_2 = QtWidgets.QLabel(self.OptimizeParam)
        self.sfValue_2.setGeometry(QtCore.QRect(10, 60, 59, 16))
        self.sfValue_2.setObjectName("sfValue_2")
        self.rmin_2 = QtWidgets.QLabel(self.OptimizeParam)
        self.rmin_2.setGeometry(QtCore.QRect(10, 100, 71, 16))
        self.rmin_2.setObjectName("rmin_2")
        self.chi2_plot = mplwidget.MplWidget(self.OptimizeParam)
        self.chi2_plot.setGeometry(QtCore.QRect(240, 20, 391, 361))
        self.chi2_plot.setObjectName("chi2_plot")
        self.ref_thickness_2 = QtWidgets.QLabel(self.OptimizeParam)
        self.ref_thickness_2.setGeometry(QtCore.QRect(10, 180, 101, 16))
        self.ref_thickness_2.setObjectName("ref_thickness_2")
        self.ref_thickness = QtWidgets.QDoubleSpinBox(self.OptimizeParam)
        self.ref_thickness.setGeometry(QtCore.QRect(140, 180, 66, 24))
        self.ref_thickness.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.ref_thickness.setMaximum(1000.0)
        self.ref_thickness.setObjectName("ref_thickness")
        self.samp_thickness_2 = QtWidgets.QLabel(self.OptimizeParam)
        self.samp_thickness_2.setGeometry(QtCore.QRect(10, 230, 121, 16))
        self.samp_thickness_2.setObjectName("samp_thickness_2")
        self.samp_thickness = QtWidgets.QDoubleSpinBox(self.OptimizeParam)
        self.samp_thickness.setGeometry(QtCore.QRect(140, 230, 66, 24))
        self.samp_thickness.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.samp_thickness.setMaximum(1000.0)
        self.samp_thickness.setObjectName("samp_thickness")
        self.optimize = QtWidgets.QPushButton(self.OptimizeParam)
        self.optimize.setGeometry(QtCore.QRect(10, 290, 75, 23))
        self.optimize.setObjectName("optimize")
        self.OptimizeParam.raise_()
        self.NonOptimizeParam.raise_()
        self.graphicPanel = QtWidgets.QGroupBox(LASDiAGUI)
        self.graphicPanel.setGeometry(QtCore.QRect(0, 0, 711, 781))
        self.graphicPanel.setTitle("")
        self.graphicPanel.setObjectName("graphicPanel")
        self.rawDataPlot = mplwidget.MplWidget(self.graphicPanel)
        self.rawDataPlot.setGeometry(QtCore.QRect(10, 10, 691, 241))
        self.rawDataPlot.setObjectName("rawDataPlot")
        self.factorPlot = mplwidget.MplWidget(self.graphicPanel)
        self.factorPlot.setGeometry(QtCore.QRect(10, 270, 691, 241))
        self.factorPlot.setObjectName("factorPlot")
        self.distfuncPlot = mplwidget.MplWidget(self.graphicPanel)
        self.distfuncPlot.setGeometry(QtCore.QRect(10, 530, 691, 241))
        self.distfuncPlot.setObjectName("distfuncPlot")

        self.retranslateUi(LASDiAGUI)
        self.expPanel.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(LASDiAGUI)

    def retranslateUi(self, LASDiAGUI):
        _translate = QtCore.QCoreApplication.translate
        LASDiAGUI.setWindowTitle(_translate("LASDiAGUI", "LASDiA"))
        self.num_interpolation_2.setText(_translate("LASDiAGUI", "Num of Points"))
        self.importData.setText(_translate("LASDiAGUI", "Import Data"))
        self.interpolationData.setText(_translate("LASDiAGUI", "Interpolation"))
        self.removePeaksData.setText(_translate("LASDiAGUI", "Remove Peaks"))
        self.expPanel.setTabText(self.expPanel.indexOf(self.fileTab), _translate("LASDiAGUI", "File"))
        self.scaleValue_2.setText(_translate("LASDiAGUI", "Scale"))
        self.numInterpolation_2.setText(_translate("LASDiAGUI", "Num of Points"))
        self.importBkg.setText(_translate("LASDiAGUI", "Import Bkg"))
        self.interpolationBkg.setText(_translate("LASDiAGUI", "Interpolation"))
        self.removePeaksBkg.setText(_translate("LASDiAGUI", "Remove Peaks"))
        self.expPanel.setTabText(self.expPanel.indexOf(self.bkgTab), _translate("LASDiAGUI", "Bkg"))
        self.xray_energy_2.setText(_translate("LASDiAGUI", "X-Ray Energy (keV)"))
        self.dacCorrection.setTitle(_translate("LASDiAGUI", "DAC Correction"))
        self.dac_thickness_2.setText(_translate("LASDiAGUI", "Anvil thickness (cm)"))
        self.dac_angle_2.setText(_translate("LASDiAGUI", "DAC Angle (deg)"))
        self.MCCCorrection.setTitle(_translate("LASDiAGUI", "MCC Correction"))
        self.ws1_2.setText(_translate("LASDiAGUI", "WS1 (cm)"))
        self.d_2.setText(_translate("LASDiAGUI", "D (cm)"))
        self.ws2_2.setText(_translate("LASDiAGUI", "WS2 (cm)"))
        self.r1_2.setText(_translate("LASDiAGUI", "R1 (cm)"))
        self.r2_2.setText(_translate("LASDiAGUI", "R2 (cm)"))
        self.expPanel.setTabText(self.expPanel.indexOf(self.geometryTab), _translate("LASDiAGUI", "Geometry"))
        self.importXYZFile.setText(_translate("LASDiAGUI", "Import XYZ file"))
        self.comboBox.setItemText(0, _translate("LASDiAGUI", "Ar"))
        self.comboBox.setItemText(1, _translate("LASDiAGUI", "C"))
        self.comboBox.setItemText(2, _translate("LASDiAGUI", "O"))
        self.comboBox.setItemText(3, _translate("LASDiAGUI", "N"))
        self.pushButton.setText(_translate("LASDiAGUI", "Add"))
        self.pushButton_2.setText(_translate("LASDiAGUI", "Edit"))
        self.pushButton_3.setText(_translate("LASDiAGUI", "Claer"))
        self.pushButton_4.setText(_translate("LASDiAGUI", "Delete"))
        self.calcSQ.setText(_translate("LASDiAGUI", "S(Q)"))
        self.calcFr.setText(_translate("LASDiAGUI", "F(r)"))
        self.expPanel.setTabText(self.expPanel.indexOf(self.sampleTab), _translate("LASDiAGUI", "Sample"))
        self.expPanel.setTabText(self.expPanel.indexOf(self.overlayTab), _translate("LASDiAGUI", "Overlay"))
        self.smoothFactor_2.setText(_translate("LASDiAGUI", "Smoothing Factor"))
        self.dampFactor_2.setText(_translate("LASDiAGUI", "Damping Factor"))
        self.iterations_2.setText(_translate("LASDiAGUI", "Num Iterations"))
        self.maxQ_2.setText(_translate("LASDiAGUI", "max Q (nm<sup>-1</sup>)"))
        self.minQ_2.setText(_translate("LASDiAGUI", "min Q (nm<sup>-1</sup>)"))
        self.QmaxInt_2.setText(_translate("LASDiAGUI", "<html><head/><body><p>Q max Int (nm<span style=\" vertical-align:super;\">-1</span>)</p></body></html>"))
        self.rho0Value_2.setText(_translate("LASDiAGUI", "Density (atm/nm<sup>3</sup>)"))
        self.sfValue_2.setText(_translate("LASDiAGUI", "Scale"))
        self.rmin_2.setText(_translate("LASDiAGUI", "r cutoff (nm)"))
        self.ref_thickness_2.setText(_translate("LASDiAGUI", "Ref Thickness (xxx)"))
        self.samp_thickness_2.setText(_translate("LASDiAGUI", "Samp Thinckness (xxx)"))
        self.optimize.setText(_translate("LASDiAGUI", "Optimize"))

from modules import mplwidget
