# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\LASDiAGUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_LASDiAGUI(object):
    def setupUi(self, LASDiAGUI):
        LASDiAGUI.setObjectName(_fromUtf8("LASDiAGUI"))
        LASDiAGUI.resize(1291, 771)
        self.expPanel = QtGui.QTabWidget(LASDiAGUI)
        self.expPanel.setGeometry(QtCore.QRect(710, 0, 571, 261))
        self.expPanel.setObjectName(_fromUtf8("expPanel"))
        self.fileTab = QtGui.QWidget()
        self.fileTab.setObjectName(_fromUtf8("fileTab"))
        self.num_interpolation_2 = QtGui.QLabel(self.fileTab)
        self.num_interpolation_2.setGeometry(QtCore.QRect(160, 180, 91, 16))
        self.num_interpolation_2.setObjectName(_fromUtf8("num_interpolation_2"))
        self.importData = QtGui.QPushButton(self.fileTab)
        self.importData.setGeometry(QtCore.QRect(10, 20, 115, 32))
        self.importData.setObjectName(_fromUtf8("importData"))
        self.interpolation = QtGui.QPushButton(self.fileTab)
        self.interpolation.setGeometry(QtCore.QRect(10, 170, 115, 32))
        self.interpolation.setObjectName(_fromUtf8("interpolation"))
        self.removePeaks = QtGui.QPushButton(self.fileTab)
        self.removePeaks.setGeometry(QtCore.QRect(10, 110, 115, 32))
        self.removePeaks.setObjectName(_fromUtf8("removePeaks"))
        self.fileSampleName = QtGui.QTextBrowser(self.fileTab)
        self.fileSampleName.setGeometry(QtCore.QRect(170, 20, 381, 31))
        self.fileSampleName.setObjectName(_fromUtf8("fileSampleName"))
        self.num_interpolation = QtGui.QSpinBox(self.fileTab)
        self.num_interpolation.setGeometry(QtCore.QRect(250, 180, 42, 22))
        self.num_interpolation.setObjectName(_fromUtf8("num_interpolation"))
        self.expPanel.addTab(self.fileTab, _fromUtf8(""))
        self.bkgTab = QtGui.QWidget()
        self.bkgTab.setObjectName(_fromUtf8("bkgTab"))
        self.fileBkgName = QtGui.QTextBrowser(self.bkgTab)
        self.fileBkgName.setGeometry(QtCore.QRect(170, 20, 381, 31))
        self.fileBkgName.setObjectName(_fromUtf8("fileBkgName"))
        self.scaleValue_2 = QtGui.QLabel(self.bkgTab)
        self.scaleValue_2.setGeometry(QtCore.QRect(170, 110, 59, 16))
        self.scaleValue_2.setObjectName(_fromUtf8("scaleValue_2"))
        self.num_interpolation_4 = QtGui.QLabel(self.bkgTab)
        self.num_interpolation_4.setGeometry(QtCore.QRect(160, 180, 91, 16))
        self.num_interpolation_4.setObjectName(_fromUtf8("num_interpolation_4"))
        self.importBkg = QtGui.QPushButton(self.bkgTab)
        self.importBkg.setGeometry(QtCore.QRect(10, 20, 115, 32))
        self.importBkg.setObjectName(_fromUtf8("importBkg"))
        self.scaleValue = QtGui.QDoubleSpinBox(self.bkgTab)
        self.scaleValue.setGeometry(QtCore.QRect(250, 110, 66, 24))
        self.scaleValue.setObjectName(_fromUtf8("scaleValue"))
        self.interpolation_2 = QtGui.QPushButton(self.bkgTab)
        self.interpolation_2.setGeometry(QtCore.QRect(10, 170, 115, 32))
        self.interpolation_2.setObjectName(_fromUtf8("interpolation_2"))
        self.removePeaks_2 = QtGui.QPushButton(self.bkgTab)
        self.removePeaks_2.setGeometry(QtCore.QRect(10, 110, 115, 32))
        self.removePeaks_2.setObjectName(_fromUtf8("removePeaks_2"))
        self.num_interpolation_3 = QtGui.QSpinBox(self.bkgTab)
        self.num_interpolation_3.setGeometry(QtCore.QRect(250, 180, 42, 22))
        self.num_interpolation_3.setObjectName(_fromUtf8("num_interpolation_3"))
        self.expPanel.addTab(self.bkgTab, _fromUtf8(""))
        self.geometryTab = QtGui.QWidget()
        self.geometryTab.setObjectName(_fromUtf8("geometryTab"))
        self.xray_energy_2 = QtGui.QLabel(self.geometryTab)
        self.xray_energy_2.setGeometry(QtCore.QRect(20, 10, 121, 16))
        self.xray_energy_2.setObjectName(_fromUtf8("xray_energy_2"))
        self.xray_energy = QtGui.QDoubleSpinBox(self.geometryTab)
        self.xray_energy.setGeometry(QtCore.QRect(130, 10, 66, 24))
        self.xray_energy.setObjectName(_fromUtf8("xray_energy"))
        self.dacCorrection = QtGui.QGroupBox(self.geometryTab)
        self.dacCorrection.setGeometry(QtCore.QRect(10, 50, 361, 51))
        self.dacCorrection.setObjectName(_fromUtf8("dacCorrection"))
        self.dac_thickness = QtGui.QDoubleSpinBox(self.dacCorrection)
        self.dac_thickness.setGeometry(QtCore.QRect(110, 20, 66, 24))
        self.dac_thickness.setDecimals(4)
        self.dac_thickness.setMaximum(99.9999)
        self.dac_thickness.setObjectName(_fromUtf8("dac_thickness"))
        self.dac_thickness_2 = QtGui.QLabel(self.dacCorrection)
        self.dac_thickness_2.setGeometry(QtCore.QRect(10, 20, 101, 16))
        self.dac_thickness_2.setObjectName(_fromUtf8("dac_thickness_2"))
        self.dac_angle = QtGui.QDoubleSpinBox(self.dacCorrection)
        self.dac_angle.setGeometry(QtCore.QRect(290, 20, 66, 24))
        self.dac_angle.setObjectName(_fromUtf8("dac_angle"))
        self.dac_angle_2 = QtGui.QLabel(self.dacCorrection)
        self.dac_angle_2.setGeometry(QtCore.QRect(190, 20, 101, 16))
        self.dac_angle_2.setObjectName(_fromUtf8("dac_angle_2"))
        self.dac_thickness.raise_()
        self.dac_thickness_2.raise_()
        self.dac_angle.raise_()
        self.dac_angle_2.raise_()
        self.MCCCorrection = QtGui.QGroupBox(self.geometryTab)
        self.MCCCorrection.setGeometry(QtCore.QRect(10, 110, 281, 111))
        self.MCCCorrection.setObjectName(_fromUtf8("MCCCorrection"))
        self.ws1_2 = QtGui.QLabel(self.MCCCorrection)
        self.ws1_2.setGeometry(QtCore.QRect(10, 20, 51, 16))
        self.ws1_2.setObjectName(_fromUtf8("ws1_2"))
        self.ws1 = QtGui.QDoubleSpinBox(self.MCCCorrection)
        self.ws1.setGeometry(QtCore.QRect(70, 20, 66, 24))
        self.ws1.setDecimals(4)
        self.ws1.setMaximum(99.9999)
        self.ws1.setObjectName(_fromUtf8("ws1"))
        self.r1 = QtGui.QDoubleSpinBox(self.MCCCorrection)
        self.r1.setGeometry(QtCore.QRect(70, 50, 66, 24))
        self.r1.setDecimals(4)
        self.r1.setMaximum(99.9999)
        self.r1.setObjectName(_fromUtf8("r1"))
        self.r2 = QtGui.QDoubleSpinBox(self.MCCCorrection)
        self.r2.setGeometry(QtCore.QRect(210, 50, 66, 24))
        self.r2.setDecimals(4)
        self.r2.setMaximum(99.9999)
        self.r2.setObjectName(_fromUtf8("r2"))
        self.d_2 = QtGui.QLabel(self.MCCCorrection)
        self.d_2.setGeometry(QtCore.QRect(10, 80, 51, 16))
        self.d_2.setObjectName(_fromUtf8("d_2"))
        self.ws2_2 = QtGui.QLabel(self.MCCCorrection)
        self.ws2_2.setGeometry(QtCore.QRect(150, 20, 51, 16))
        self.ws2_2.setObjectName(_fromUtf8("ws2_2"))
        self.ws2 = QtGui.QDoubleSpinBox(self.MCCCorrection)
        self.ws2.setGeometry(QtCore.QRect(210, 20, 66, 24))
        self.ws2.setDecimals(4)
        self.ws2.setMaximum(99.9999)
        self.ws2.setObjectName(_fromUtf8("ws2"))
        self.r1_2 = QtGui.QLabel(self.MCCCorrection)
        self.r1_2.setGeometry(QtCore.QRect(10, 50, 51, 16))
        self.r1_2.setObjectName(_fromUtf8("r1_2"))
        self.d = QtGui.QDoubleSpinBox(self.MCCCorrection)
        self.d.setGeometry(QtCore.QRect(70, 80, 66, 24))
        self.d.setDecimals(4)
        self.d.setMaximum(99.9999)
        self.d.setObjectName(_fromUtf8("d"))
        self.r2_2 = QtGui.QLabel(self.MCCCorrection)
        self.r2_2.setGeometry(QtCore.QRect(150, 50, 51, 16))
        self.r2_2.setObjectName(_fromUtf8("r2_2"))
        self.expPanel.addTab(self.geometryTab, _fromUtf8(""))
        self.sampleTab = QtGui.QWidget()
        self.sampleTab.setObjectName(_fromUtf8("sampleTab"))
        self.pushButton_5 = QtGui.QPushButton(self.sampleTab)
        self.pushButton_5.setGeometry(QtCore.QRect(430, 190, 115, 32))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.comboBox = QtGui.QComboBox(self.sampleTab)
        self.comboBox.setGeometry(QtCore.QRect(10, 70, 69, 22))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.pushButton = QtGui.QPushButton(self.sampleTab)
        self.pushButton.setGeometry(QtCore.QRect(10, 20, 75, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.sampleTab)
        self.pushButton_2.setGeometry(QtCore.QRect(100, 20, 75, 23))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.sampleTab)
        self.pushButton_3.setGeometry(QtCore.QRect(280, 20, 75, 23))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_4 = QtGui.QPushButton(self.sampleTab)
        self.pushButton_4.setGeometry(QtCore.QRect(190, 20, 75, 23))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.expPanel.addTab(self.sampleTab, _fromUtf8(""))
        self.overlayTab = QtGui.QWidget()
        self.overlayTab.setObjectName(_fromUtf8("overlayTab"))
        self.expPanel.addTab(self.overlayTab, _fromUtf8(""))
        self.analysisPanel = QtGui.QGroupBox(LASDiAGUI)
        self.analysisPanel.setGeometry(QtCore.QRect(710, 270, 571, 491))
        self.analysisPanel.setObjectName(_fromUtf8("analysisPanel"))
        self.NonOptimizeParam = QtGui.QGroupBox(self.analysisPanel)
        self.NonOptimizeParam.setGeometry(QtCore.QRect(0, 0, 571, 81))
        self.NonOptimizeParam.setTitle(_fromUtf8(""))
        self.NonOptimizeParam.setObjectName(_fromUtf8("NonOptimizeParam"))
        self.smooth_factor = QtGui.QDoubleSpinBox(self.NonOptimizeParam)
        self.smooth_factor.setGeometry(QtCore.QRect(100, 10, 66, 24))
        self.smooth_factor.setObjectName(_fromUtf8("smooth_factor"))
        self.smooth_factor_2 = QtGui.QLabel(self.NonOptimizeParam)
        self.smooth_factor_2.setGeometry(QtCore.QRect(10, 10, 91, 16))
        self.smooth_factor_2.setObjectName(_fromUtf8("smooth_factor_2"))
        self.maxQ = QtGui.QDoubleSpinBox(self.NonOptimizeParam)
        self.maxQ.setGeometry(QtCore.QRect(400, 50, 66, 24))
        self.maxQ.setObjectName(_fromUtf8("maxQ"))
        self.damping_factor_2 = QtGui.QLabel(self.NonOptimizeParam)
        self.damping_factor_2.setGeometry(QtCore.QRect(10, 50, 91, 16))
        self.damping_factor_2.setObjectName(_fromUtf8("damping_factor_2"))
        self.iteration_2 = QtGui.QLabel(self.NonOptimizeParam)
        self.iteration_2.setGeometry(QtCore.QRect(180, 10, 101, 16))
        self.iteration_2.setObjectName(_fromUtf8("iteration_2"))
        self.iteration = QtGui.QDoubleSpinBox(self.NonOptimizeParam)
        self.iteration.setGeometry(QtCore.QRect(260, 10, 66, 24))
        self.iteration.setObjectName(_fromUtf8("iteration"))
        self.damping_factor = QtGui.QDoubleSpinBox(self.NonOptimizeParam)
        self.damping_factor.setGeometry(QtCore.QRect(100, 50, 66, 24))
        self.damping_factor.setObjectName(_fromUtf8("damping_factor"))
        self.minQ = QtGui.QDoubleSpinBox(self.NonOptimizeParam)
        self.minQ.setGeometry(QtCore.QRect(400, 10, 66, 24))
        self.minQ.setObjectName(_fromUtf8("minQ"))
        self.maxQ_2 = QtGui.QLabel(self.NonOptimizeParam)
        self.maxQ_2.setGeometry(QtCore.QRect(350, 50, 59, 16))
        self.maxQ_2.setObjectName(_fromUtf8("maxQ_2"))
        self.minQ_2 = QtGui.QLabel(self.NonOptimizeParam)
        self.minQ_2.setGeometry(QtCore.QRect(350, 10, 59, 16))
        self.minQ_2.setObjectName(_fromUtf8("minQ_2"))
        self.OptimizeParam = QtGui.QGroupBox(self.analysisPanel)
        self.OptimizeParam.setGeometry(QtCore.QRect(0, 80, 571, 411))
        self.OptimizeParam.setTitle(_fromUtf8(""))
        self.OptimizeParam.setObjectName(_fromUtf8("OptimizeParam"))
        self.sf_value = QtGui.QDoubleSpinBox(self.OptimizeParam)
        self.sf_value.setGeometry(QtCore.QRect(100, 90, 66, 24))
        self.sf_value.setObjectName(_fromUtf8("sf_value"))
        self.rmin = QtGui.QDoubleSpinBox(self.OptimizeParam)
        self.rmin.setGeometry(QtCore.QRect(100, 130, 66, 24))
        self.rmin.setObjectName(_fromUtf8("rmin"))
        self.rho0_value_2 = QtGui.QLabel(self.OptimizeParam)
        self.rho0_value_2.setGeometry(QtCore.QRect(10, 50, 59, 16))
        self.rho0_value_2.setObjectName(_fromUtf8("rho0_value_2"))
        self.rho0_value = QtGui.QDoubleSpinBox(self.OptimizeParam)
        self.rho0_value.setGeometry(QtCore.QRect(100, 50, 66, 24))
        self.rho0_value.setObjectName(_fromUtf8("rho0_value"))
        self.sf_value_2 = QtGui.QLabel(self.OptimizeParam)
        self.sf_value_2.setGeometry(QtCore.QRect(10, 90, 59, 16))
        self.sf_value_2.setObjectName(_fromUtf8("sf_value_2"))
        self.rmin_2 = QtGui.QLabel(self.OptimizeParam)
        self.rmin_2.setGeometry(QtCore.QRect(10, 130, 59, 16))
        self.rmin_2.setObjectName(_fromUtf8("rmin_2"))
        self.chi2_plot = MatplotlibWidget(self.OptimizeParam)
        self.chi2_plot.setGeometry(QtCore.QRect(180, 50, 391, 361))
        self.chi2_plot.setObjectName(_fromUtf8("chi2_plot"))
        self.ref_thickness_2 = QtGui.QLabel(self.OptimizeParam)
        self.ref_thickness_2.setGeometry(QtCore.QRect(10, 210, 71, 16))
        self.ref_thickness_2.setObjectName(_fromUtf8("ref_thickness_2"))
        self.ref_thickness = QtGui.QDoubleSpinBox(self.OptimizeParam)
        self.ref_thickness.setGeometry(QtCore.QRect(100, 210, 66, 24))
        self.ref_thickness.setObjectName(_fromUtf8("ref_thickness"))
        self.samp_thickness_2 = QtGui.QLabel(self.OptimizeParam)
        self.samp_thickness_2.setGeometry(QtCore.QRect(10, 260, 81, 16))
        self.samp_thickness_2.setObjectName(_fromUtf8("samp_thickness_2"))
        self.samp_thickness = QtGui.QDoubleSpinBox(self.OptimizeParam)
        self.samp_thickness.setGeometry(QtCore.QRect(100, 260, 66, 24))
        self.samp_thickness.setObjectName(_fromUtf8("samp_thickness"))
        self.OptimizeParam.raise_()
        self.NonOptimizeParam.raise_()
        self.graphicPanel = QtGui.QGroupBox(LASDiAGUI)
        self.graphicPanel.setGeometry(QtCore.QRect(0, 0, 711, 761))
        self.graphicPanel.setTitle(_fromUtf8(""))
        self.graphicPanel.setObjectName(_fromUtf8("graphicPanel"))
        self.matplotlibwidget = MatplotlibWidget(self.graphicPanel)
        self.matplotlibwidget.setGeometry(QtCore.QRect(10, 10, 691, 241))
        self.matplotlibwidget.setObjectName(_fromUtf8("matplotlibwidget"))
        self.matplotlibwidget_2 = MatplotlibWidget(self.graphicPanel)
        self.matplotlibwidget_2.setGeometry(QtCore.QRect(10, 260, 691, 241))
        self.matplotlibwidget_2.setObjectName(_fromUtf8("matplotlibwidget_2"))
        self.matplotlibwidget_3 = MatplotlibWidget(self.graphicPanel)
        self.matplotlibwidget_3.setGeometry(QtCore.QRect(10, 510, 691, 241))
        self.matplotlibwidget_3.setObjectName(_fromUtf8("matplotlibwidget_3"))

        self.retranslateUi(LASDiAGUI)
        self.expPanel.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(LASDiAGUI)

    def retranslateUi(self, LASDiAGUI):
        LASDiAGUI.setWindowTitle(_translate("LASDiAGUI", "LASDiA", None))
        self.num_interpolation_2.setText(_translate("LASDiAGUI", "Num of Points", None))
        self.importData.setText(_translate("LASDiAGUI", "Import Data", None))
        self.interpolation.setText(_translate("LASDiAGUI", "Interpolation", None))
        self.removePeaks.setText(_translate("LASDiAGUI", "Remove Peaks", None))
        self.expPanel.setTabText(self.expPanel.indexOf(self.fileTab), _translate("LASDiAGUI", "File", None))
        self.scaleValue_2.setText(_translate("LASDiAGUI", "Scale", None))
        self.num_interpolation_4.setText(_translate("LASDiAGUI", "Num of Points", None))
        self.importBkg.setText(_translate("LASDiAGUI", "Import Bkg", None))
        self.interpolation_2.setText(_translate("LASDiAGUI", "Interpolation", None))
        self.removePeaks_2.setText(_translate("LASDiAGUI", "Remove Peaks", None))
        self.expPanel.setTabText(self.expPanel.indexOf(self.bkgTab), _translate("LASDiAGUI", "Bkg", None))
        self.xray_energy_2.setText(_translate("LASDiAGUI", "X-Ray Energy (keV)", None))
        self.dacCorrection.setTitle(_translate("LASDiAGUI", "DAC Correction", None))
        self.dac_thickness_2.setText(_translate("LASDiAGUI", "Anvil thickness (cm)", None))
        self.dac_angle_2.setText(_translate("LASDiAGUI", "DAC Angle (deg)", None))
        self.MCCCorrection.setTitle(_translate("LASDiAGUI", "MCC Correction", None))
        self.ws1_2.setText(_translate("LASDiAGUI", "WS1 (cm)", None))
        self.d_2.setText(_translate("LASDiAGUI", "D (cm)", None))
        self.ws2_2.setText(_translate("LASDiAGUI", "WS2 (cm)", None))
        self.r1_2.setText(_translate("LASDiAGUI", "R1 (cm)", None))
        self.r2_2.setText(_translate("LASDiAGUI", "R2 (cm)", None))
        self.expPanel.setTabText(self.expPanel.indexOf(self.geometryTab), _translate("LASDiAGUI", "Geometry", None))
        self.pushButton_5.setText(_translate("LASDiAGUI", "Import XYZ file", None))
        self.comboBox.setItemText(0, _translate("LASDiAGUI", "Ar", None))
        self.comboBox.setItemText(1, _translate("LASDiAGUI", "C", None))
        self.comboBox.setItemText(2, _translate("LASDiAGUI", "O", None))
        self.comboBox.setItemText(3, _translate("LASDiAGUI", "N", None))
        self.pushButton.setText(_translate("LASDiAGUI", "Add", None))
        self.pushButton_2.setText(_translate("LASDiAGUI", "Edit", None))
        self.pushButton_3.setText(_translate("LASDiAGUI", "Claer", None))
        self.pushButton_4.setText(_translate("LASDiAGUI", "Delete", None))
        self.expPanel.setTabText(self.expPanel.indexOf(self.sampleTab), _translate("LASDiAGUI", "Sample", None))
        self.expPanel.setTabText(self.expPanel.indexOf(self.overlayTab), _translate("LASDiAGUI", "Overlay", None))
        self.smooth_factor_2.setText(_translate("LASDiAGUI", "Smoothing Factor", None))
        self.damping_factor_2.setText(_translate("LASDiAGUI", "Damp Factor", None))
        self.iteration_2.setText(_translate("LASDiAGUI", "Num Iterations", None))
        self.maxQ_2.setText(_translate("LASDiAGUI", "max Q", None))
        self.minQ_2.setText(_translate("LASDiAGUI", "min Q", None))
        self.rho0_value_2.setText(_translate("LASDiAGUI", "Density", None))
        self.sf_value_2.setText(_translate("LASDiAGUI", "Scale", None))
        self.rmin_2.setText(_translate("LASDiAGUI", "r cutoff", None))
        self.ref_thickness_2.setText(_translate("LASDiAGUI", "Ref Thickness", None))
        self.samp_thickness_2.setText(_translate("LASDiAGUI", "Samp Thinckness", None))

from matplotlibwidget import MatplotlibWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    LASDiAGUI = QtGui.QMainWindow()
    ui = Ui_LASDiAGUI()
    ui.setupUi(LASDiAGUI)
    LASDiAGUI.show()
    sys.exit(app.exec_())