# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modules/gui/LASDiA_gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.5-snapshot-d5f52f3403f7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_LASDiA(object):
    def setupUi(self, LASDiA):
        LASDiA.setObjectName(_fromUtf8("LASDiA"))
        LASDiA.resize(1280, 751)
        self.label_2 = QtGui.QLabel(LASDiA)
        self.label_2.setGeometry(QtCore.QRect(300, 10, 71, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.Fr = MplWidget(LASDiA)
        self.Fr.setGeometry(QtCore.QRect(650, 510, 481, 191))
        self.Fr.setObjectName(_fromUtf8("Fr"))
        self.layoutWidget = QtGui.QWidget(LASDiA)
        self.layoutWidget.setGeometry(QtCore.QRect(650, 10, 144, 211))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.LoadData = QtGui.QPushButton(self.layoutWidget)
        self.LoadData.setObjectName(_fromUtf8("LoadData"))
        self.verticalLayout.addWidget(self.LoadData)
        self.LoadBkg = QtGui.QPushButton(self.layoutWidget)
        self.LoadBkg.setObjectName(_fromUtf8("LoadBkg"))
        self.verticalLayout.addWidget(self.LoadBkg)
        self.CalcSQ = QtGui.QPushButton(self.layoutWidget)
        self.CalcSQ.setObjectName(_fromUtf8("CalcSQ"))
        self.verticalLayout.addWidget(self.CalcSQ)
        self.Calcgr = QtGui.QPushButton(self.layoutWidget)
        self.Calcgr.setObjectName(_fromUtf8("Calcgr"))
        self.verticalLayout.addWidget(self.Calcgr)
        self.label = QtGui.QLabel(LASDiA)
        self.label.setGeometry(QtCore.QRect(0, 10, 101, 111))
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8("modules/gui/ESRF.jpg")))
        self.label.setScaledContents(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.RawData = MplWidget(LASDiA)
        self.RawData.setGeometry(QtCore.QRect(120, 40, 481, 191))
        self.RawData.setObjectName(_fromUtf8("RawData"))
        self.groupBox_2 = QtGui.QGroupBox(LASDiA)
        self.groupBox_2.setGeometry(QtCore.QRect(900, 320, 201, 151))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.Optimization = QtGui.QPushButton(self.groupBox_2)
        self.Optimization.setGeometry(QtCore.QRect(0, 100, 144, 32))
        self.Optimization.setObjectName(_fromUtf8("Optimization"))
        self.widget = QtGui.QWidget(self.groupBox_2)
        self.widget.setGeometry(QtCore.QRect(10, 30, 133, 62))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_6 = QtGui.QLabel(self.widget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_5.addWidget(self.label_6)
        self.label_7 = QtGui.QLabel(self.widget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_5.addWidget(self.label_7)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.Iteration = QtGui.QSpinBox(self.widget)
        self.Iteration.setObjectName(_fromUtf8("Iteration"))
        self.verticalLayout_6.addWidget(self.Iteration)
        self.rcuttoff = QtGui.QDoubleSpinBox(self.widget)
        self.rcuttoff.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.rcuttoff.setObjectName(_fromUtf8("rcuttoff"))
        self.verticalLayout_6.addWidget(self.rcuttoff)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.label_8 = QtGui.QLabel(LASDiA)
        self.label_8.setGeometry(QtCore.QRect(1120, 10, 131, 111))
        self.label_8.setText(_fromUtf8(""))
        self.label_8.setPixmap(QtGui.QPixmap(_fromUtf8("modules/gui/CEA.png")))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.groupBox = QtGui.QGroupBox(LASDiA)
        self.groupBox.setGeometry(QtCore.QRect(840, 120, 251, 191))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.Minimization = QtGui.QPushButton(self.groupBox)
        self.Minimization.setGeometry(QtCore.QRect(60, 160, 115, 32))
        self.Minimization.setObjectName(_fromUtf8("Minimization"))
        self.widget1 = QtGui.QWidget(self.groupBox)
        self.widget1.setGeometry(QtCore.QRect(20, 30, 179, 130))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_11 = QtGui.QLabel(self.widget1)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_4.addWidget(self.label_11)
        self.label_12 = QtGui.QLabel(self.widget1)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_4.addWidget(self.label_12)
        self.label_14 = QtGui.QLabel(self.widget1)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_4.addWidget(self.label_14)
        self.label_13 = QtGui.QLabel(self.widget1)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_4.addWidget(self.label_13)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.rho0LowerLim = QtGui.QDoubleSpinBox(self.widget1)
        self.rho0LowerLim.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.rho0LowerLim.setObjectName(_fromUtf8("rho0LowerLim"))
        self.verticalLayout_3.addWidget(self.rho0LowerLim)
        self.rho0UpperLim = QtGui.QDoubleSpinBox(self.widget1)
        self.rho0UpperLim.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.rho0UpperLim.setObjectName(_fromUtf8("rho0UpperLim"))
        self.verticalLayout_3.addWidget(self.rho0UpperLim)
        self.sLowerLim = QtGui.QDoubleSpinBox(self.widget1)
        self.sLowerLim.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.sLowerLim.setObjectName(_fromUtf8("sLowerLim"))
        self.verticalLayout_3.addWidget(self.sLowerLim)
        self.sUpperLim = QtGui.QDoubleSpinBox(self.widget1)
        self.sUpperLim.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.sUpperLim.setObjectName(_fromUtf8("sUpperLim"))
        self.verticalLayout_3.addWidget(self.sUpperLim)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.SQ = MplWidget(LASDiA)
        self.SQ.setGeometry(QtCore.QRect(120, 270, 481, 191))
        self.SQ.setObjectName(_fromUtf8("SQ"))
        self.groupBox_5 = QtGui.QGroupBox(LASDiA)
        self.groupBox_5.setGeometry(QtCore.QRect(820, 20, 261, 81))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.Elements = QtGui.QComboBox(self.groupBox_5)
        self.Elements.setGeometry(QtCore.QRect(0, 50, 104, 26))
        self.Elements.setObjectName(_fromUtf8("Elements"))
        self.Elements.addItem(_fromUtf8(""))
        self.Elements.addItem(_fromUtf8(""))
        self.Elements.addItem(_fromUtf8(""))
        self.Elements.addItem(_fromUtf8(""))
        self.Multiplicity = QtGui.QSpinBox(self.groupBox_5)
        self.Multiplicity.setGeometry(QtCore.QRect(140, 50, 47, 24))
        self.Multiplicity.setObjectName(_fromUtf8("Multiplicity"))
        self.label_9 = QtGui.QLabel(self.groupBox_5)
        self.label_9.setGeometry(QtCore.QRect(10, 30, 59, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.groupBox_5)
        self.label_10.setGeometry(QtCore.QRect(140, 30, 81, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_4 = QtGui.QLabel(LASDiA)
        self.label_4.setGeometry(QtCore.QRect(300, 470, 59, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(LASDiA)
        self.label_5.setGeometry(QtCore.QRect(650, 470, 100, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gr = MplWidget(LASDiA)
        self.gr.setGeometry(QtCore.QRect(120, 510, 481, 191))
        self.gr.setObjectName(_fromUtf8("gr"))
        self.label_3 = QtGui.QLabel(LASDiA)
        self.label_3.setGeometry(QtCore.QRect(300, 240, 59, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.groupBox_4 = QtGui.QGroupBox(LASDiA)
        self.groupBox_4.setGeometry(QtCore.QRect(650, 320, 161, 71))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.widget2 = QtGui.QWidget(self.groupBox_4)
        self.widget2.setGeometry(QtCore.QRect(10, 20, 137, 41))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.ALForm = QtGui.QCheckBox(self.widget2)
        self.ALForm.setObjectName(_fromUtf8("ALForm"))
        self.verticalLayout_2.addWidget(self.ALForm)
        self.FZForm = QtGui.QCheckBox(self.widget2)
        self.FZForm.setObjectName(_fromUtf8("FZForm"))
        self.verticalLayout_2.addWidget(self.FZForm)

        self.retranslateUi(LASDiA)
        QtCore.QMetaObject.connectSlotsByName(LASDiA)

    def retranslateUi(self, LASDiA):
        LASDiA.setWindowTitle(_translate("LASDiA", "LASDiA", None))
        self.label_2.setText(_translate("LASDiA", "Raw Data", None))
        self.LoadData.setText(_translate("LASDiA", "Load Data", None))
        self.LoadBkg.setText(_translate("LASDiA", "Load Bkg", None))
        self.CalcSQ.setText(_translate("LASDiA", "Calc S(Q)", None))
        self.Calcgr.setText(_translate("LASDiA", "Calc g(r)", None))
        self.groupBox_2.setTitle(_translate("LASDiA", "F(r) Optimization Parameters", None))
        self.Optimization.setText(_translate("LASDiA", "Optimization", None))
        self.label_6.setText(_translate("LASDiA", "Iteration", None))
        self.label_7.setText(_translate("LASDiA", "r cut-off", None))
        self.groupBox.setTitle(_translate("LASDiA", "Parameters for minimization", None))
        self.Minimization.setText(_translate("LASDiA", "Minimization", None))
        self.label_11.setText(_translate("LASDiA", "rho0 lower limit", None))
        self.label_12.setText(_translate("LASDiA", "rho0 upper limit", None))
        self.label_14.setText(_translate("LASDiA", "s lower limit", None))
        self.label_13.setText(_translate("LASDiA", "s upper limit", None))
        self.groupBox_5.setTitle(_translate("LASDiA", "Sample Composition", None))
        self.Elements.setItemText(0, _translate("LASDiA", "Ar", None))
        self.Elements.setItemText(1, _translate("LASDiA", "C", None))
        self.Elements.setItemText(2, _translate("LASDiA", "O", None))
        self.Elements.setItemText(3, _translate("LASDiA", "Si", None))
        self.label_9.setText(_translate("LASDiA", "Elements", None))
        self.label_10.setText(_translate("LASDiA", "Multiplicity", None))
        self.label_4.setText(_translate("LASDiA", "g(r)", None))
        self.label_5.setText(_translate("LASDiA", "F(r) optimization", None))
        self.label_3.setText(_translate("LASDiA", "S(Q)", None))
        self.groupBox_4.setTitle(_translate("LASDiA", "Formalism", None))
        self.ALForm.setText(_translate("LASDiA", "Ashcroft-Langreth", None))
        self.FZForm.setText(_translate("LASDiA", "Faber-Ziman", None))

from modules.gui.mplwidget import MplWidget
